mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from django.views.generic import  TemplateView
from . import views

app_name = 'polls'
urlpatterns = [
    path('detail/<int:question_id>', views.detailView, name = "detail"),
    path('list/', views.viewlist, name='view_list'),
    path('', views.index, name = "index"),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

mysite/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Question
def index(request):
    myname = "Ngoc Tuan"
    taisan1 = ["Dien thoai", "May Tinh", "May Bay", "Nhieu tien"]
    context = {"name": myname, "taisan": taisan1}
    return render(request, "polls/index.html", context)

def viewlist(request):
    #get_object_or_404(Question, pk=1)
    #list_question = get_object_or_404(Question, pk=4)
    list_question = Question.objects.all()
    context = {"dsquest": list_question}
    return render(request, "polls/question_list.html", context)
def detailView(request, question_id):
    q = Question.objects.get(pk = question_id)
    return render(request, "polls/detail_question.html", {"qs" : q})

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport"
    content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
  <meta name="shopee:git-sha" content="8cae90bf3bf0c7afa6e4ee95ffe297ccb92686fd">
  <meta name="shopee:version" content="pc-v4.33.0">
  <script>
    window.__LOCALE__ = 'VN';
    window.__ENV__ = 'live';
  </script>
  <script>function showBody(){document&&document.body&&(document.body.style.visibility="visible")}var SHORT_URL_MAX_LENGTH=256,pathname=location&&location.pathname;if("/"!==pathname&&pathname.length<SHORT_URL_MAX_LENGTH&&""===location.hash&&-1===pathname.indexOf("-")&&0===pathname.lastIndexOf("/")){document&&document.body&&(document.body.style.visibility="hidden"),setTimeout(showBody,5e3);var xhr=new XMLHttpRequest;xhr.open("GET","/api/v0/is_short_url/?path="+pathname.replace("/","")),xhr.setRequestHeader("Content-Type","application/json"),xhr.setRequestHeader("Accept","application/json"),xhr.onreadystatechange=function(){if(4===this.readyState)if(200===this.status)if(JSON.parse(this.responseText).error)showBody();else{var e=document.createElement("a");e.href=location.href,e.search+="?"===e.search[0]?"&__classic__=1":"?__classic__=1",location.href=e.href}else showBody()},xhr.send()}</script>
  <script>if(window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,window.PerformanceObserver){var observer=new window.PerformanceObserver(function(e){for(var r=e.getEntries(),n=0;n<r.length;n++){var a=r[n],i=a.name,t=Math.round(a.startTime+a.duration);ga("send",{hitType:"timing",timingCategory:"Performance Metrics",timingVar:i,timingValue:t})}});observer.observe({entryTypes:["paint"]})}</script>
  <script>window.prometheusGetChunks=function(){return window.webpackJsonp};</script>
  <!-- Open search -->
    <link type="application/opensearchdescription+xml" rel="search" href="https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/b5dd2df53adc0ae0b1ab06cbe99ab873.xml" />
    <link
      rel="dns-prefetch"
      href="//cf.shopee.vn/"
    />
    <link
      rel="dns-prefetch"
      href="//deo.shopeemobile.com/shopee/"
    />
    <link
      rel="dns-prefetch"
      href="//cv.shopee.vn/"
    />
  <script>dataLayer = [];</script>
  <script>(function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({
        'gtm.start':
          new Date().getTime(), event: 'gtm.js', country: 'vn'
      }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-WJZQSJF');</script>
  <script>!function(c,f){if(self&&performance){var t,o,i,e=[],r={passive:!0,capture:!0},n=new Date,a="pointerup",u="pointercancel";m(c),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){e.push(n),s()}}function p(n,e){t||(t=e,o=n,i=new Date,m(f),s())}function s(){0<=o&&o<i-n&&(e.forEach(function(n){n(o,t)}),e=[])}function l(n){if(n.cancelable){var e=(1e12<n.timeStamp?new Date:performance.now())-n.timeStamp;"pointerdown"===n.type?function(n,e){function t(){p(n,e),i()}function o(){i()}function i(){f(a,t,r),f(u,o,r)}c(a,t,r),c(u,o,r)}(e,n):p(e,n)}}function m(e){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(n){e(n,l,r)})}}(addEventListener,removeEventListener);</script>
  <script>function shopeeInitFirebase(e){var n=document.createElement("script"),a=!1,i=!1;n.async=1,n.src="https://www.gstatic.com/firebasejs/6.5.0/firebase-performance-standalone.js";var t=document.getElementsByTagName("script")[0];function r(){a&&i&&window.firebase&&(window._globalFirebasePerformanceEntry=window.firebase.initializeApp(e).performance())}t.parentNode.insertBefore(n,t),window.addEventListener("load",function(){i=!0,r()}),n.onload=function(){a=!0,r()}}</script>
  <script>
    shopeeInitFirebase({"appId":"1:808332928752:web:7980b4158343fde7","apiKey":"AIzaSyCZnRmQRNJOw3NFAfJsyKixBYoN61P1MYQ","authDomain":"shopee-ad86f.firebaseapp.com","databaseURL":"https://shopee-ad86f.firebaseio.com","projectId":"shopee-ad86f","storageBucket":"shopee-ad86f.appspot.com","messagingSenderId":"808332928752"});
  </script>
<link href="https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/bundle.5d6cf0f060523804c4ae.css" rel="stylesheet"></head>
<body>
  <noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WJZQSJF" height="0" width="0"
      style="display:none;visibility:hidden"></iframe>
  </noscript>
  <div id="main"></div>
  <div id="modal"></div>
  <div class="shopee__kZMc3xKQ4ab">
    <div class="shopee__3o9SfdFxcoiKs"></div>
  </div>
  <div class="shopee__fo0dKsgoukkfcaik">
    <div class="shopee-modal-xbcA3dFx0Ck"></div>
  </div>
<script type="text/javascript" src="https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/modules~bundle.fd101b7782963e4538f7.js"></script><script type="text/javascript" src="https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/bundle.9238d9a5d0912bcde8ed.js"></script></body>
</html>
    {% block content123 %}
    {% endblock %}
</div>
</body>
</html>

mysite/polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}
{% block content123 %}
    {% if qs %}
        <ul>
        {% for item in qs.choice_set.all %}
            <li> <input type="radio" value = "{{ item.id}}"> {{ item.choice_text}} </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content123 %}
    <h1>Day la template</h1>
    <p>Chao cac ban minh la <b>{{ name }} </b></p>
<h2>Tai san cua toi gom: </h2>
<u1>
    {% for item in taisan %}
        {% if item != 'May Tinh' %}
            <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
</u1>
{% endblock %}

mysite/polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}
{% block content123 %}
    {% if dsquest %}
        {% for item in dsquest %}
            <p> {{ item.question_text }} </p>
        {% endfor %}
    {% else %}
        <h3 style="color: red;"> Không có câu hỏi nào !!! </h3>
    {% endif %}
{% endblock %}